### ISSUE TITLE
Fix Release_StaticCrt tests

### ISSUE THREAD

**Issue by KindDragon** [KindDragon/vld#10]
Previous work on PR #8

Doesn't work v90-v110 Release_StaticCrt tests

Current build results https://ci.appveyor.com/project/KindDragon/vld/build/127

/cc @ioannis-e

**Comment by KindDragon** [comment]
Fixed in fed574d

**Comment by ioannis-e** [comment]
See my [comments](https://github.com/KindDragon/vld/commit/b6bef88a8e908e2936e001cbe3109bfb51b5cff8#commitcomment-14243869)
