### ISSUE TITLE
Broken build in VS2013

### ISSUE THREAD

**Issue by ioannis-e** [KindDragon/vld#12]
b195c320ab11f82ce30d308ad8affaf675f4d1b9 has broken build in VS2013
Tried to fix with f82e1481b8314f42e47368c23a07f3b33573f654 but fails in appveyor

**Comment by KindDragon** [comment]
Everything fine on appveyor https://ci.appveyor.com/project/KindDragon/vld/build/138

> b195c32 has broken build in VS2013

You mean that you can't build it locally?
[How build VLD using previous version of VS](https://github.com/KindDragon/vld/wiki/How-build-VLD-using-previous-version-of-VS)

**Comment by KindDragon** [comment]
`.\change_toolset.ps1` shouldn't change VLD, libformat toolset because VLD can't be built with VS2008 toolset, because of that `VldToolset` should be changed manually.

**Comment by ioannis-e** [comment]
i see.

But it builds ok with VS2013 so i guess ``change_tooset.ps1`` should change everyting for VS2010 to VS2015  and only behave as described above for VS2008 and below..

Doesn't this make better sense ?

**Comment by KindDragon** [comment]
I will release Vld builded with VS2015, so I need test with this toolset.
I added `.\change_toolset.ps1` -force option to simplify changing toolset.

**Comment by KindDragon** [comment]
BTW, I want release new version but one user report false positive leaks with new code https://gist.github.com/akaStiX/5f9a18102fa9610fc276 :cry: on VS2015 with gtest. I can't reproduce that leaks ATM.

**Comment by ioannis-e** [comment]
I will see if i can repro.

I made another PR regarding the capture context, maybe we could merge before release ?

**Comment by KindDragon** [comment]
I will merge it after AppVeyor check it
