### ISSUE TITLE
Installation of vld-2.5-setup.exe on 32-bit WinXP fails

### ISSUE THREAD

**Issue by tbeu** [KindDragon/vld#19]
The v2.5 installer fails on 32-bit WinXP SP3 with an `Internal error: Cannot access 64-bit registry keys on this version of Windows.`. The v2.4rc2 installer runs without errors.

**Comment by tbeu** [comment]
See http://vld.codeplex.com/workitem/10607

**Comment by SomaWorker** [comment]
same Problem with the version 2.5.1.

**Comment by serge-sb** [comment]
Same problem with the version 2.5.1 on Windows 7 x86.

**Comment by phuclv90** [comment]
Related #38
