### ISSUE TITLE
direct/indirect leaks

### ISSUE THREAD

**Issue by Trass3r** [KindDragon/vld#20]
Does/could vld distinguish between direct and indirect leaks like LeakSanitizer does?

**Comment by ioannis-e** [comment]
How do you define direct and indirect leaks?

**Comment by Trass3r** [comment]
Well if A owns an instance of B and A is leaked B will also indirectly be.

**Comment by KindDragon** [comment]
No, it can't distinguish that leaks. We monitor only allocation, LeakSanitizer/Valgrind monitor all memory
