### ISSUE TITLE
How do I uninstall this thing?

### ISSUE THREAD

**Issue by decare** [KindDragon/vld#81]
Uninstalled Visual Leak detector, but still when creating Win32 C++ projects I always get "C:\Program Files (x86)\Visual Leak Detector\include" item in Additional Include Directories in project properties.
Same for "C:\Program Files (x86)\Visual Leak Detector\lib\Win32" in Additional Library Directories.
These settings are set by default for all Visual Studio 2013 C++ projects.

How do I get rid of these default settings?
Thanks

**Comment by KindDragon** [comment]
Check this page https://github.com/KindDragon/vld/wiki/Using-Visual-Leak-Detector and remove VLD directory from property page

**Comment by decare** [comment]
That didn't help, sorry.
There are no VLD directories in VC++ property pages.
Any more suggestions?

I am still getting "C:\Program Files (x86)\Visual Leak Detector\include" in "Additional Include Directories" by default.
Tried grepping VisualStudio config files (actually all text/binary files) - no luck.

**Comment by KindDragon** [comment]
We modify this property sheets for this https://github.com/KindDragon/vld/blob/master/setup/vld-setup.iss#L424-L434

So check inside `%LOCALAPPDATA%\Microsoft\MSBuild\v4.0\` directory: `Microsoft.Cpp.Win32.user.props` and `Microsoft.Cpp.x64.user.props`

**Comment by decare** [comment]
Problem solved! Thanks a lot!
See if you can change the uninstaller so that it can undo these modifications in the property sheets.
